// Bilingual strings — English + Tamil
export type Language = 'en' | 'ta';

export const Strings: Record<Language, Record<string, string>> = {
  en: {
    appName: 'KisanFlow',
    tagline: 'Smart Procurement, Simplified',
    getStarted: 'Get Started',
    login: 'Login',
    logout: 'Logout',
    register: 'Register',
    mobileNumber: 'Mobile Number',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify OTP',
    enterOtp: 'Enter OTP',
    otpSent: 'OTP sent to your mobile number',
    selectRole: 'Select Your Role',
    farmer: 'Farmer',
    officer: 'Officer',
    admin: 'Admin',
    dashboard: 'Dashboard',
    myBookings: 'My Bookings',
    bookSlot: 'Book Slot',
    myQueue: 'My Queue',
    payments: 'Payments',
    profile: 'Profile',
    cropRegistration: 'Crop Registration',
    selectCrop: 'Select Crop',
    variety: 'Variety',
    quantity: 'Expected Quantity (kg)',
    harvestDate: 'Harvest Date',
    preferredCentre: 'Preferred Centre',
    availableSlots: 'Available Slots',
    slotFull: 'FULL',
    slotsLeft: 'slots left',
    yourToken: 'Your Token',
    queuePosition: 'Queue Position',
    farmersAhead: 'Farmers Ahead',
    estimatedWait: 'Estimated Wait',
    centreStatus: 'Centre Status',
    operating: 'Operating Normally',
    moderate: 'Moderate Load',
    high: 'High Load',
    minutes: 'minutes',
    tokenNumber: 'Token Number',
    crop: 'Crop',
    weight: 'Weight',
    date: 'Date',
    time: 'Time',
    status: 'Status',
    weighment: 'Weighment',
    qualityCheck: 'Quality Check',
    procurement: 'Procurement',
    payment: 'Payment',
    grossWeight: 'Gross Weight',
    tare: 'Tare Weight',
    netWeight: 'Net Weight',
    moisture: 'Moisture (%)',
    foreignMatter: 'Foreign Matter (%)',
    damagedGrain: 'Damaged Grain (%)',
    qualityGrade: 'Quality Grade',
    accepted: 'Accepted',
    rejected: 'Rejected',
    procurementReceipt: 'Procurement Receipt',
    estimatedValue: 'Estimated Value',
    paymentStatus: 'Payment Status',
    billGenerated: 'Bill Generated',
    paymentSubmitted: 'Payment Submitted',
    bankProcessing: 'Bank Processing',
    paymentCredited: 'Payment Credited',
    pending: 'Pending',
    completed: 'Completed',
    processing: 'Processing',
    waitingFarmers: 'Waiting',
    processingNow: 'Processing',
    completedToday: 'Completed Today',
    avgProcessTime: 'Avg. Processing',
    nowServing: 'Now Serving',
    callNext: 'Call Next',
    markArrived: 'Mark Arrived',
    startWeighment: 'Start Weighment',
    submitQuality: 'Submit Quality',
    completeProcurement: 'Complete',
    updatePayment: 'Update Payment',
    centreMap: 'Centre Map',
    analytics: 'Analytics',
    totalFarmers: 'Total Farmers',
    todayBookings: "Today's Bookings",
    activeCentres: 'Active Centres',
    congested: 'Congested',
    booked: 'Booked',
    arrived: 'Arrived',
    called: 'Called',
    paid: 'Paid',
    name: 'Name',
    village: 'Village',
    district: 'District',
    farmerId: 'Farmer ID',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    noData: 'No data available',
    aiPrediction: 'AI Prediction',
    recommendedSlot: 'Recommended Slot',
    lowCrowd: 'Low Crowd',
    notifications: 'Notifications',
    queueApproaching: 'Your turn is approaching!',
    pleaseArrive: 'Please reach the centre within 20 minutes.',
    onboard1Title: 'Smart Slot Booking',
    onboard1Desc: 'Book your procurement slot from home. No more travelling to check availability.',
    onboard2Title: 'Virtual Queue',
    onboard2Desc: 'Track your token and queue position live. Arrive only when your turn is near.',
    onboard3Title: 'Payment Tracking',
    onboard3Desc: 'Monitor every step from weighment to payment credit in real time.',
    paddy: 'Paddy',
    wheat: 'Wheat',
    maize: 'Maize',
    sorghum: 'Sorghum',
    millet: 'Millet',
    cotton: 'Cotton',
    soybean: 'Soybean',
    groundnut: 'Groundnut',
  },
  ta: {
    appName: 'கிசான்ஃப்ளோ',
    tagline: 'சிறந்த கொள்முதல், எளிமையாக',
    getStarted: 'தொடங்குங்கள்',
    login: 'உள்நுழை',
    logout: 'வெளியேறு',
    register: 'பதிவு செய்',
    mobileNumber: 'மொபைல் எண்',
    sendOtp: 'OTP அனுப்பு',
    verifyOtp: 'OTP சரிபார்',
    enterOtp: 'OTP உள்ளிடு',
    otpSent: 'உங்கள் மொபைலுக்கு OTP அனுப்பப்பட்டது',
    selectRole: 'உங்கள் பாத்திரம் தேர்ந்தெடு',
    farmer: 'விவசாயி',
    officer: 'அலுவலர்',
    admin: 'நிர்வாகி',
    dashboard: 'டாஷ்போர்டு',
    myBookings: 'என் முன்பதிவுகள்',
    bookSlot: 'ஸ்லாட் பதிவு',
    myQueue: 'என் வரிசை',
    payments: 'கட்டணங்கள்',
    profile: 'சுயவிவரம்',
    cropRegistration: 'பயிர் பதிவு',
    selectCrop: 'பயிர் தேர்ந்தெடு',
    variety: 'ரகம்',
    quantity: 'எதிர்பார்க்கப்பட்ட அளவு (கிலோ)',
    harvestDate: 'அறுவடை தேதி',
    preferredCentre: 'விரும்பிய மையம்',
    availableSlots: 'கிடைக்கும் ஸ்லாட்கள்',
    slotFull: 'நிரம்பியது',
    slotsLeft: 'ஸ்லாட்கள் உள்ளன',
    yourToken: 'உங்கள் டோக்கன்',
    queuePosition: 'வரிசை நிலை',
    farmersAhead: 'முன்னால் விவசாயிகள்',
    estimatedWait: 'மதிப்பீட்டு காத்திருப்பு',
    centreStatus: 'மைய நிலை',
    operating: 'சாதாரணமாக இயங்குகிறது',
    moderate: 'மிதமான சுமை',
    high: 'அதிக சுமை',
    minutes: 'நிமிடங்கள்',
    tokenNumber: 'டோக்கன் எண்',
    crop: 'பயிர்',
    weight: 'எடை',
    date: 'தேதி',
    time: 'நேரம்',
    status: 'நிலை',
    weighment: 'எடை அளவீடு',
    qualityCheck: 'தரம் சரிபார்ப்பு',
    procurement: 'கொள்முதல்',
    payment: 'கட்டணம்',
    grossWeight: 'மொத்த எடை',
    tare: 'ட்டேர் எடை',
    netWeight: 'நிகர எடை',
    moisture: 'ஈரப்பதம் (%)',
    foreignMatter: 'அந்நிய பொருள் (%)',
    damagedGrain: 'சேதமடைந்த தானியம் (%)',
    qualityGrade: 'தர வகுப்பு',
    accepted: 'ஏற்றுக்கொள்ளப்பட்டது',
    rejected: 'நிராகரிக்கப்பட்டது',
    procurementReceipt: 'கொள்முதல் ரசீது',
    estimatedValue: 'மதிப்பீட்டு மதிப்பு',
    paymentStatus: 'கட்டண நிலை',
    billGenerated: 'பில் உருவாக்கப்பட்டது',
    paymentSubmitted: 'கட்டணம் சமர்ப்பிக்கப்பட்டது',
    bankProcessing: 'வங்கி செயலாக்கம்',
    paymentCredited: 'கட்டணம் வரவு வைக்கப்பட்டது',
    pending: 'நிலுவையில்',
    completed: 'முடிந்தது',
    processing: 'செயலில்',
    waitingFarmers: 'காத்திருக்கும்',
    processingNow: 'செயலாக்கம்',
    completedToday: 'இன்று முடிந்தது',
    avgProcessTime: 'சராசரி செயலாக்க நேரம்',
    nowServing: 'இப்போது சேவை',
    callNext: 'அடுத்தவரை அழைக்க',
    markArrived: 'வந்தது குறி',
    startWeighment: 'எடை தொடங்கு',
    submitQuality: 'தரம் சமர்ப்பி',
    completeProcurement: 'முடி',
    updatePayment: 'கட்டணம் புதுப்பி',
    centreMap: 'மைய வரைபடம்',
    analytics: 'பகுப்பாய்வு',
    totalFarmers: 'மொத்த விவசாயிகள்',
    todayBookings: 'இன்றைய முன்பதிவுகள்',
    activeCentres: 'செயலில் மையங்கள்',
    congested: 'நெரிசல்',
    booked: 'முன்பதிவு',
    arrived: 'வந்தது',
    called: 'அழைக்கப்பட்டது',
    paid: 'கட்டணம் செலுத்தப்பட்டது',
    name: 'பெயர்',
    village: 'கிராமம்',
    district: 'மாவட்டம்',
    farmerId: 'விவசாயி அடையாளம்',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    confirm: 'உறுதிப்படுத்து',
    back: 'பின்செல்',
    next: 'அடுத்து',
    submit: 'சமர்ப்பி',
    noData: 'தரவு இல்லை',
    aiPrediction: 'AI கணிப்பு',
    recommendedSlot: 'பரிந்துரைக்கப்பட்ட ஸ்லாட்',
    lowCrowd: 'குறைந்த நெரிசல்',
    notifications: 'அறிவிப்புகள்',
    queueApproaching: 'உங்கள் முறை நெருங்குகிறது!',
    pleaseArrive: 'தயவுசெய்து 20 நிமிடங்களுக்குள் மையத்தை அடையுங்கள்.',
    onboard1Title: 'சிறந்த ஸ்லாட் முன்பதிவு',
    onboard1Desc: 'வீட்டிலிருந்தே கொள்முதல் ஸ்லாட் பதிவு செய்யுங்கள். கிடைக்கும் தன்மை சரிபார்க்க பயணிக்க வேண்டாம்.',
    onboard2Title: 'மெய்நிகர் வரிசை',
    onboard2Desc: 'உங்கள் டோக்கன் மற்றும் வரிசை நிலையை நேரடியாக கண்காணியுங்கள்.',
    onboard3Title: 'கட்டண கண்காணிப்பு',
    onboard3Desc: 'எடை அளவீட்டிலிருந்து கட்டண வரவு வரை ஒவ்வொரு படியையும் நேரடியாக கண்காணியுங்கள்.',
    paddy: 'நெல்',
    wheat: 'கோதுமை',
    maize: 'மக்காச்சோளம்',
    sorghum: 'சோளம்',
    millet: 'தினை',
    cotton: 'பருத்தி',
    soybean: 'சோயாபீன்',
    groundnut: 'வேர்க்கடலை',
  },
};
